#!/bin/bash
bold=$(tput bold)
#!/bin/bash
# init

scriptname="$(realpath $0)"

function editscript(){
echo "scriptname: $scriptname"
if [[ "$1" == "edit" ]]; then
 (/usr/bin/nano "$scriptname")
 exit
fi
}

editscript "$1"

normal=$(tput sgr0)

if [[ -d "$1" ]]
 then
	echo $bold
	rmdir "$1"

#	tput bold
#	echo
	echo $bold
	echo "Directory of $1:"
	ls -alF "$1"
	echo
#	$normal
	find "$1"
	echo
#elif [[ -d "$1" ]]
# then
	rm -rI "$1"
	echo $normal
elif [[ -f "$1" ]]
 then
	echo
	printf "\"$1\""" is a file:  "$bold
	ls -ltr "$1"
	echo $normal
#	echo "Do you wish to delete the file?"
#	select yn in "Yes" "No"; do
#		case $yn in
#    			Yes ) rm "$1"; break;;
#			No ) exit;;
#		esac
#	done


	printf 'rmr: remove this file? (y/n) '
	old_stty_cfg=$(stty -g)
	stty raw -echo ; answer=$(head -c 1) ; stty "$old_stty_cfg" # Careful playing with stty
	if [ "$answer" != "${answer#[Yy]}" ];then
    		rm "$1"; printf "\n\n"; ls -ltr "$1";
	else
    		printf "\n\n%s \n" "$(ls -ltr "$1")";
	fi

fi

printf "\n\n"
